#pragma once
#include <array>
#include <string>
#include <vector>
#include <cstdint>
#include <fstream>
#include <sstream>
#include <stdint.h>
#include <algorithm>
#include <functional>
#include <unordered_map>
#include <iostream>